# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Add comment
on:
  issues:
    types:
      - opened
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your
            contribution! :sparkles:
     - name: Add to index
        uses: ./.github/actions/hello-world-action
        with:
          app_id: ${{ secrets.ALGOLIA_APP_ID }}
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as 
          api_key: ${{ secrets.ALGOLIA_API_KEY }}
          # The index name. 
          index_name: secretlair-issues
          # The index file path relative to repo root.
          record: "{firstname: 'Jimmie', lastname: 'Barninger', objectID: 'myID1'}"